-- CreateTable
CREATE TABLE "order_records" (
    "id" SERIAL NOT NULL,
    "status" TEXT DEFAULT 'Open Order',
    "customer" TEXT,
    "agreement_number" TEXT,
    "po_number" TEXT,
    "release_number" TEXT,
    "lot_number" TEXT,
    "ncr" BOOLEAN DEFAULT false,
    "sgs_po_number" TEXT,
    "product_description" TEXT,
    "comments" TEXT,
    "part_number" TEXT,
    "fg_number" TEXT,
    "process" TEXT,
    "required_bio_tests" TEXT,
    "date_agreement_po_rcvd" TIMESTAMP(3),
    "customer_supplied_ware" TEXT,
    "qty_rcvd_cs_ware" INTEGER,
    "date_cs_ware_received" TIMESTAMP(3),
    "date_cs_receiving_docs_submitted" TIMESTAMP(3),
    "date_cs_documents_saved_to_server" TIMESTAMP(3),
    "date_dac_assigned" TIMESTAMP(3),
    "date_wo_created_qa" TIMESTAMP(3),
    "date_wo_approved" TIMESTAMP(3),
    "date_material_pulled" TIMESTAMP(3),
    "expected_start_week" TEXT,
    "start_date" TIMESTAMP(3),
    "started_date_mm_yy" TEXT,
    "actual_bio_ship_date" TIMESTAMP(3),
    "all_results_received" BOOLEAN,
    "date_bfs_test_reports_rcvd" TIMESTAMP(3),
    "date_dts_test_reports_rcvd" TIMESTAMP(3),
    "date_lalval_test_reports_rcvd" TIMESTAMP(3),
    "date_rlal_test_reports_rcvd" TIMESTAMP(3),
    "completion_date" TIMESTAMP(3),
    "completion_date_boxed" TIMESTAMP(3),
    "reconciled_date_mm_yy" TEXT,
    "date_wo_submitted_to_qa" TIMESTAMP(3),
    "reviewed_date_mm_yy" TEXT,
    "date_wo_submitted_to_production" TIMESTAMP(3),
    "quarantine_waiver_created" TIMESTAMP(3),
    "type_of_cert_required" TEXT,
    "total_order_yield" INTEGER,
    "processed_yield_difference_pct" DOUBLE PRECISION,
    "date_request_for_cert_sent" TIMESTAMP(3),
    "date_cert_created" TIMESTAMP(3),
    "cert_reviewed_and_approved" TIMESTAMP(3),
    "quantity_shipped_so_far" INTEGER,
    "quarantine" BOOLEAN DEFAULT false,
    "quantity_particulate_samples" INTEGER,
    "date_particulate_samples_collected" TIMESTAMP(3),
    "quantity_sgs_samples" INTEGER,
    "date_sgs_samples_collected" TIMESTAMP(3),
    "order_quantity_eaches" INTEGER,
    "order_quantity_trays_bags" DOUBLE PRECISION,
    "quantity_per_tray_bag" INTEGER,
    "total_order_balance" INTEGER,
    "week_code_start" TEXT,
    "price_per_unit" DOUBLE PRECISION,
    "sublot_price_expected_non_shipped" DOUBLE PRECISION,
    "sublot_price_yield_non_shipped" DOUBLE PRECISION,
    "week_code_yield" TEXT,
    "expected_yield_price_diff" DOUBLE PRECISION,
    "shipped_price_per_unit" DOUBLE PRECISION,
    "sublot_price_expected" DOUBLE PRECISION,
    "sublot_price_yield" DOUBLE PRECISION,
    "order_balance_value" DOUBLE PRECISION,
    "quarantine_release_required" BOOLEAN,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "order_records_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "shipping_logs" (
    "id" SERIAL NOT NULL,
    "status" TEXT,
    "customer" TEXT,
    "agreement_po_number" TEXT,
    "lot_number" TEXT,
    "shipper_number" TEXT,
    "product_description" TEXT,
    "part_number" TEXT,
    "fg_number" TEXT,
    "quantity_per_tray_bag" INTEGER,
    "quarantine_shipment" BOOLEAN,
    "forecasted_amount" INTEGER,
    "total_order_yield" INTEGER,
    "shipped_so_far" INTEGER,
    "order_balance" INTEGER,
    "ship_date" TIMESTAMP(3),
    "ship_quantity" INTEGER,
    "week_code_shipped" TEXT,
    "price_per_unit" DOUBLE PRECISION,
    "sublot_price_yield" DOUBLE PRECISION,
    "sublot_price_shipped" DOUBLE PRECISION,
    "yield_shipped_price_diff" DOUBLE PRECISION,
    "sublot_price_forecasted" DOUBLE PRECISION,
    "shipped_so_far_value" DOUBLE PRECISION,
    "forecasted_shipped_price_diff" DOUBLE PRECISION,
    "partial_shipment" BOOLEAN,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "shipping_logs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ncr_records" (
    "id" SERIAL NOT NULL,
    "customer" TEXT,
    "lot_number" TEXT,
    "ncr_lot_number" TEXT,
    "product_description" TEXT,
    "part_number" TEXT,
    "comments" TEXT,
    "ncr_created_date" TIMESTAMP(3),
    "wash_start_date" TIMESTAMP(3),
    "boxed_date" TIMESTAMP(3),
    "reconciled_date" TIMESTAMP(3),
    "reviewed_date" TIMESTAMP(3),
    "total_order_yield" INTEGER,
    "cert_request_sent_date" TIMESTAMP(3),
    "certified_date" TIMESTAMP(3),
    "ship_date" TIMESTAMP(3),
    "ship_quantity" INTEGER,
    "total_order_balance" INTEGER,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ncr_records_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "quarantine_records" (
    "id" SERIAL NOT NULL,
    "customer" TEXT,
    "release_number" TEXT,
    "lot_number" TEXT,
    "product_description" TEXT,
    "cleaning_start_date" TIMESTAMP(3),
    "quarantine_release_date" TIMESTAMP(3),
    "quarantine_released" BOOLEAN DEFAULT false,
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "quarantine_records_pkey" PRIMARY KEY ("id")
);
